// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_404-trigger.tsx";
import * as $2 from "./routes/_404.tsx";
import * as $3 from "./routes/_500.tsx";
import * as $4 from "./routes/_middleware-array.ts";
import * as $5 from "./routes/_middleware.ts";
import * as $6 from "./routes/about.tsx";
import * as $7 from "./routes/api/joke.ts";
import * as $8 from "./routes/api/random-uuid.ts";
import * as $9 from "./routes/countdown.tsx";
import * as $10 from "./routes/counter02.tsx";
import * as $11 from "./routes/github/[username].tsx";
import * as $12 from "./routes/greet/[name].tsx";
import * as $13 from "./routes/html.tsx";
import * as $14 from "./routes/index.tsx";
import * as $15 from "./routes/myHandler.ts";
import * as $16 from "./routes/old/[...wildcard].tsx";
import * as $17 from "./routes/plain.tsx";
import * as $18 from "./routes/project.tsx";
import * as $19 from "./routes/search.tsx";
import * as $20 from "./routes/static.tsx";
import * as $21 from "./routes/x.ts";
import * as $$0 from "./islands/Countdown.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Counter02.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_404-trigger.tsx": $1,
    "./routes/_404.tsx": $2,
    "./routes/_500.tsx": $3,
    "./routes/_middleware-array.ts": $4,
    "./routes/_middleware.ts": $5,
    "./routes/about.tsx": $6,
    "./routes/api/joke.ts": $7,
    "./routes/api/random-uuid.ts": $8,
    "./routes/countdown.tsx": $9,
    "./routes/counter02.tsx": $10,
    "./routes/github/[username].tsx": $11,
    "./routes/greet/[name].tsx": $12,
    "./routes/html.tsx": $13,
    "./routes/index.tsx": $14,
    "./routes/myHandler.ts": $15,
    "./routes/old/[...wildcard].tsx": $16,
    "./routes/plain.tsx": $17,
    "./routes/project.tsx": $18,
    "./routes/search.tsx": $19,
    "./routes/static.tsx": $20,
    "./routes/x.ts": $21,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Counter02.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
